GET http://localhost:7777/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUyNDQ4NTIsImV4cCI6MTcxNTI0NDkxMiwiYXVkIjoiNjYzYzhmMzQxZGE2MDk0NDJlOGY5ZDU3IiwiaXNzIjoiamh1bnRhLmNvbSJ9.TLUpeczd35LtkM6wjm5rNJq7NsPnoaPj5Peq1TX7bhs
###
POST http://localhost:7777/auth/login
Content-Type: application/json

{   
    "name": "Junry",
    "email": "junrybuenavista@yahoo.com",
    "password": "Junry123"
}

###
POST http://localhost:7777/auth/register
Content-Type: application/json

{   
    "name": "Junry Buenavista",
    "email": "junrybuenavista1@yahoo.com",
    "password": "Junry1231"
}

###
POST http://localhost:7777/auth/refresh-token
Content-Type: application/json

{   
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTUyMzgxMzYsImV4cCI6MTc0Njc5NTczNiwiYXVkIjoiNjYzNWM1NTc2MTFhZWVmNjFlZGMyNTMyIiwiaXNzIjoiamh1bnRhLmNvbSJ9.ZDbf1pjjlPPJn-nSOt4EWMQA3D88LNYSgURLBruAYzA"
}

###
DELETE  http://localhost:7777/auth/logout


####
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTQ4MDE5MzMsImV4cCI6MTc0NjM1OTUzMywiYXVkIjoiNjYzNWM1NTc2MTFhZWVmNjFlZGMyNTMyIiwiaXNzIjoiamh1bnRhLmNvbSJ9._4-eJwvRPtV7-pZm65Jluhmz0ooXDR-NC8EYeQ5UyCI