
POST http://localhost:7777/student
Content-Type: application/json

{  
    "userId": "664ae227d00fb6b772acb2b0",
    "first_name": "testff",
    "last_name": "test4d",
    "middle_name": "test2",
    "age": "56",
    "gender": "ff",
    "address": "test2",
    "coursegradeId": "6659d3231c364bdd54a17dbe"
}
###
POST http://localhost:7777/student/delete/66595c77bae13f40a44b2bbd
Content-Type: application/json


###
POST http://localhost:7777/student/list
Content-Type: application/json

{  
    "userId": "664ae227d00fb6b772acb2b0",
    "coursegradeId":"6659a473ea2a16f83931beb5"
}
###
POST http://localhost:7777/auth/login
Content-Type: application/json

{  

    "email": "junrybuenavista@yahoo.com",
    "password": "Junry1231"
}

###
POST http://localhost:7777/auth/register
Content-Type: application/json

{   
    "name": "Junry Buenavista",
    "email": "junrybuenavista@yahoo.com",
    "password": "Junry1231"
}

###
POST http://localhost:7777/auth/refresh-token
Content-Type: application/json

{   
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTU5NDA0MjEsImV4cCI6MTc0NzQ5ODAyMSwiYXVkIjoiNjY0MzMyM2E5NjZjNDg0ZmY0MzViNDRlIiwiaXNzIjoiamh1bnRhLmNvbSJ9.sMCzmlCo4iEm97mUTo3j5hHzxLb0fvoibEGBVdUdv40"
}

###
DELETE http://localhost:7777/auth/logout
Content-Type: application/json

{   
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTU5NDIzMTMsImV4cCI6MTc0NzQ5OTkxMywiYXVkIjoiNjY0MzMyM2E5NjZjNDg0ZmY0MzViNDRlIiwiaXNzIjoiamh1bnRhLmNvbSJ9.lXUH4mQDLDnrQC9yCVvKuDgYJS7MauCdC9xJWX-Ha_o"
}
####
